version: '3'
services:
  
  api: 
    command: go run main.go
    ports:
      - 3001:3001
    environment:
      - NUM_CPU_CORES=8
      - DB_URI=root:root@tcp(db:3306)/real_estate
      - API_PORT=3001
    volumes:
      - .:/app

  db:
    ports: 
      - 3316:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db-data:/var/lib/mysql
    
volumes:
  db-data: