version: '3'
services:
  
  api: 
    command: go run main.go
    ports:
      - 3001:3001
    environment:
      - APP_NUM_CPU_CORES=8
      - DB_URI=root:root@tcp(db:3306)/real_estate
      - REDIS_URI=redis:6379
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3001
    volumes:
      - .:/app

  db:
    ports: 
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db-data:/var/lib/mysql

  redis:
    volumes:
      - cache-data:/data
    
volumes:
  db-data:
  cache-data: