version: '3'
services:
  
  api: 
    build: .
    container_name: api
    restart: on-failure
    depends_on:
      - db
    networks:
      - db-tier

  db:
    build: ./db
    hostname: db
    container_name: db
    restart: always
    networks:
      - db-tier
  
volumes:
  db-data:

networks:
  db-tier:
