version: '3'
services:

  gateway:
    build: ./gateway
    ports:
      - 80:80
    restart: on-failure
    depends_on:
      - api
      - db
      - redis
    networks:
      - db-tier
  
  api: 
    build: .
    hostname: api
    container_name: api
    restart: on-failure
    depends_on:
      - db
    networks:
      - db-tier
      - cache-tier

  db:
    build: ./db
    hostname: db
    container_name: db
    restart: always
    networks:
      - db-tier
      - cache-tier

  redis:
    image: redis:alpine
    hostname: redis
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports: ["6379"]
    networks:
      - cache-tier

networks:
  db-tier:
  cache-tier:
