apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template: 
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: yura2033/real_estate:1.0.0
        name: api
        command: ["go", "run", "main.go"]
        ports:
        - containerPort: 3001
        env:
          - name: DB_URI
            valueFrom: 
              secretKeyRef:
                name: api-secret
                key: dbUri
          - name: REDIS_URI
            valueFrom: 
              secretKeyRef:
                name: api-secret
                key: redisUri
          - name: SERVER_HOST
            valueFrom: 
              secretKeyRef:
                name: api-secret
                key: serverHost
        imagePullPolicy: IfNotPresent