apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  labels:
    app: api
type: Opaque
data:
  serverHost: MC4wLjAuMAo=
  dbUri: cm9vdDpyb290QHRjcChkYi1wcm94eTozMzA2KS9yZWFsX2VzdGF0ZQo=
  redisUri: cmVkaXM6NjM3OQo=