apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  # labels:
  #   app: api
    # env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template: 
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: my-app
        image: yura2033/real_estate:1.0.0
        ports:
        - containerPort: 3001
        env:
          - name: DB_URI
            value: root:root@tcp(db:3306)/real_estate
          - name: REDIS_URI
            value: redis:6379
          - name: SERVER_HOST
            value: 0.0.0.0
          - name: SERVER_PORT
            value: "3001"
        imagePullPolicy: Always
        command: ["go", "run", "main.go"]
