apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template: 
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: yura2033/real_estate:1.0.1
        name: api
        command: ["go", "run", "main.go"]
        ports:
        - containerPort: 3001
        env:
          - name: DB_URI
            valueFrom: 
              configMapKeyRef:
                name: api-config
                key: dbUri
          - name: REDIS_URI
            valueFrom: 
              configMapKeyRef:
                name: api-config
                key: redisUri
          - name: SERVER_HOST
            valueFrom: 
              configMapKeyRef:
                name: api-config
                key: serverHost
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 65
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 3001
          initialDelaySeconds:  60
          periodSeconds: 2
        imagePullPolicy: IfNotPresent