apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: redis
spec:
  containers:
  - image: redis:alpine
    name: redis
    command:
      - redis-server
    ports:
    - containerPort: 6379
    resources:
      limits:
        cpu: "0.1"
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /data
      name: data
  volumes:
    - name: data
      emptyDir: {}