apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        tier: db
    spec:
      containers:
      - image: mysql:5.6
        name: db
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        ports:
        - containerPort: 3306
        imagePullPolicy: Never
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pv-claim
