package consts

const (
	USER_ALREADY_EXISTS     = "USER_ALREADY_EXISTS"
	BAD_REQUEST             = "BAD_REQUEST"
	GET_PRESIGNED_URL_ERROR = "GET_PRESIGNED_URL_ERROR"
	INTERNAL                = "INTERNAL_SERVER_ERROR"
)
