-- MySQL Script generated by MySQL Workbench
-- пт, 21-лют-2020 17:14:23 +0200
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema real_estate
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `real_estate` ;

-- -----------------------------------------------------
-- Schema real_estate
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `real_estate` DEFAULT CHARACTER SET utf8 ;
USE `real_estate` ;

-- -----------------------------------------------------
-- Table `real_estate`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `real_estate`.`city` ;

CREATE TABLE IF NOT EXISTS `real_estate`.`city` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `real_estate`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `real_estate`.`user` ;

CREATE TABLE IF NOT EXISTS `real_estate`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(45) NOT NULL,
  `password` CHAR(60) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `avatar` VARCHAR(255) NULL,
  `city_id` INT NULL,
  `is_suspended` TINYINT(1) NULL DEFAULT 0,
  `is_admin` TINYINT(1) NULL DEFAULT 0,
  `is_confirmed` TINYINT(1) NULL DEFAULT 0,
  `insert_dt` DATETIME NULL DEFAULT NOW(),
  `update_dt` TIMESTAMP NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ak_nickname` (`nickname` ASC),
  INDEX `fk_user_city_idx` (`city_id` ASC),
  CONSTRAINT `fk_user_city`
    FOREIGN KEY (`city_id`)
    REFERENCES `real_estate`.`city` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `real_estate`.`estate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `real_estate`.`estate` ;

CREATE TABLE IF NOT EXISTS `real_estate`.`estate` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price` INT NOT NULL,
  `is_rent` TINYINT(1) NULL DEFAULT 0,
  `city_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `selling_date` DATE NULL,
  `insert_dt` DATETIME NULL DEFAULT NOW(),
  `update_dt` TIMESTAMP NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_estate_city_idx` (`city_id` ASC),
  INDEX `fk_estate_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_estate_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `real_estate`.`city` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_estate_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `real_estate`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `real_estate`.`file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `real_estate`.`file` ;

CREATE TABLE IF NOT EXISTS `real_estate`.`file` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ak_url` (`url` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `real_estate`.`estate_file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `real_estate`.`estate_file` ;

CREATE TABLE IF NOT EXISTS `real_estate`.`estate_file` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estate_id` INT NOT NULL,
  `file_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estate_file_estate1_idx` (`estate_id` ASC),
  INDEX `fk_estate_file_file1_idx` (`file_id` ASC),
  UNIQUE INDEX `ak_estate_file` (`estate_id` ASC, `file_id` ASC),
  CONSTRAINT `fk_estate_file_estate1`
    FOREIGN KEY (`estate_id`)
    REFERENCES `real_estate`.`estate` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_estate_file_file1`
    FOREIGN KEY (`file_id`)
    REFERENCES `real_estate`.`file` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `real_estate`.`user_estate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `real_estate`.`user_estate` ;

CREATE TABLE IF NOT EXISTS `real_estate`.`user_estate` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `estate_id` INT NOT NULL,
  INDEX `fk_user_estate_user1_idx` (`user_id` ASC),
  INDEX `fk_user_estate_estate1_idx` (`estate_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ak_user_estate` (`user_id` ASC, `estate_id` ASC),
  CONSTRAINT `fk_user_estate_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `real_estate`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_estate_estate1`
    FOREIGN KEY (`estate_id`)
    REFERENCES `real_estate`.`estate` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
