server:
  host: 127.0.0.1
  port: 3001

db:
 uri: root:123@tcp(127.0.0.1:3306)/real_estate

aws:
  bucket_name:
  access_key_id: 
  secret_access_key:

fileStore:
  fileWhiteList:
    - "image/png"
    - "image/jpg"
    - "image/jpeg"
    
    